###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "fahmi@mail.com",
  "password" : "fahmi123"
}

###
POST http://localhost:3000/users/register
Content-Type: application/json

{ 
  "email":"fahmi@mail.com", 
  "phoneNumber":"081234567890", 
  "city":"Jakarta", 
  "zip":"12345", 
  "message":"Hello World", 
  "password":"fahmi123", 
  "username":"fahmi123", 
  "address":"Jl. Jalan" 
}

###
POST http://localhost:3000/admins/login
Content-Type: application/json

{  
  "email":"admin@mail.com",
  "password":"admin123"
}

###
GET http://localhost:3000/orders/
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiZmFobWlAbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjgzMDM0OTM0fQ.wkVi0jrn81pt56M_6PLZb07dKfNndbjhf24t3MjgS8Q

###
GET http://localhost:3000/orders/21
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiZmFobWlAbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjgzMDM0OTM0fQ.wkVi0jrn81pt56M_6PLZb07dKfNndbjhf24t3MjgS8Q


### AS USER
POST http://localhost:3000/orders/
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiZmFobWlAbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjgzMDM0OTM0fQ.wkVi0jrn81pt56M_6PLZb07dKfNndbjhf24t3MjgS8Q

{
  "pickUpLoc":"58997 Lerdahl Alley",
  "dropOffLoc":"92598 Fuller Junction",
  "pickUpDate":"13-Jun-2022",
  "dropOffDate":"13-Jul-2022",
  "pickUpTime":"13-Jun-2022 07:00:00",
  "carId":15
}

### AS USER
PUT http://localhost:3000/orders/21
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiZmFobWlAbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjgzMDM0OTM0fQ.wkVi0jrn81pt56M_6PLZb07dKfNndbjhf24t3MjgS8Q

### AS USER
DELETE http://localhost:3000/orders/21
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiZmFobWlAbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjgzMDM0OTM0fQ.wkVi0jrn81pt56M_6PLZb07dKfNndbjhf24t3MjgS8Q

### AS ADMIN
GET http://localhost:3000/orders/
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjgzMDMzNTExfQ.fSbUjbVmnxlN3uA1e19BT63OizNU4OCZCnSoeJIlmiI

### AS ADMIN
GET http://localhost:3000/orders/2
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjgzMDMzNTExfQ.fSbUjbVmnxlN3uA1e19BT63OizNU4OCZCnSoeJIlmiI

### AS ADMIN
POST http://localhost:3000/orders/
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjgzMDMzNTExfQ.fSbUjbVmnxlN3uA1e19BT63OizNU4OCZCnSoeJIlmiI

{
  "pickUpLoc":"Test1",
  "dropOffLoc":"Test1",
  "pickUpDate":"13-Jun-2022",
  "dropOffDate":"13-Jul-2022",
  "pickUpTime":"13-Jun-2022 07:00:00",
  "carId":2
}

### AS ADMIN
PUT http://localhost:3000/orders/23
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjgzMDMzNTExfQ.fSbUjbVmnxlN3uA1e19BT63OizNU4OCZCnSoeJIlmiI

{
  "pickUpLoc":"Test1.1",
  "dropOffLoc":"Test1.1",
  "pickUpDate":"13-Jun-2022",
  "dropOffDate":"13-Jul-2022",
  "pickUpTime":"13-Jun-2022 07:00:00",
  "carId":2
}

### AS ADMIN
DELETE http://localhost:3000/orders/23
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjgzMDMzNTExfQ.fSbUjbVmnxlN3uA1e19BT63OizNU4OCZCnSoeJIlmiI
